apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-operators-list.yaml
    target:
      kind: ApplicationSet
      name: cluster-operators